parameters:
    cache_adapter: cache.adapter.apcu

framework:
    cache:
        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        app: '%cache_adapter%'
